### ISSUE TITLE
Москва

### ISSUE THREAD

**Issue by CortaVortex** [ornalogy/static-world-map.ornalogy.ru#10]
{
  "title": "<Москва>",
  "version": "1.0",
  "osmid": <2555133>,
  "center": [ <55.7505412>, <37.6174782> ],
  "markers": {
    "FH90IA": [ <5>, <55.799841>, <37.471363> ],
    "HE73OX": [ <5>, <55.806510>, <37.449866> ],
    "3LRTIS": [ <5>, <55.800984>, <37.445130> ],
    "8QLZ1S": [ <5>, <55.799870>, <37.445033> ],
    "2YD9MV": [ <5>, <55.795873>, <37.457120> ],
    "ZFQ6IN": [ <7>, <55.803521>, <37.469194> ],
    "QBFI7X": [ <7>, <55.805736>, <37.475716> ],
    "CHHE73": [ <7>, <55.812947>, <37.472497> ],
  }
}

**Comment by IgorNovozhilov** [comment]
https://static-world-map.ornalogy.ru/?moscow
