### ISSUE TITLE
sevastopol

### ISSUE THREAD

**Issue by jally7** [ornalogy/static-world-map.ornalogy.ru#2]
{
  "title": "Sevastopol",
  "version": "1.0",
  "center": [44.616538, 33.525286],
  "markers": {
    "7eb66f1d-48ca-4fe5-95e8-957a173ef190": [ 10, 44.6164, 33.5268 ],
	"f6358558-9a27-4752-a57b-ef4b40b05814": [ 5, 44.6129, 33.5284 ],
	"8ae9aeb7-a396-4a86-8c0c-731d5b128665": [ 5, 44.6124, 33.5285 ]    
  }
}

**Comment by IgorNovozhilov** [comment]
https://static-world-map.ornalogy.ru/?sevastopol
