### ISSUE TITLE
Ижевск

### ISSUE THREAD

**Issue by 4monya** [ornalogy/static-world-map.ornalogy.ru#3]
{
  "title": "Ижевск",
  "version": "1.0",
  "center": [ 56.8528719576079, 53.20706210554608 ],
  "markers": {
    "IndustrialD1": [ 5, 56.900776, 53.245694 ],
    "IndustrialD2": [ 5, 56.901122, 53.255814 ],
    "IndustrialD3": [ 5, 56.899651, 53.260750 ],
    "IndustrialD4": [ 5, 56.897045, 53.256830 ],
    "IndustrialD5": [ 5, 56.891737, 53.259928 ],
    "IndustrialD6": [ 5, 56.891928, 53.243347 ],
    "IndustrialD7": [ 5, 56.891928, 53.243347 ],

   
  }
}

**Comment by IgorNovozhilov** [comment]
https://static-world-map.ornalogy.ru/?izhevsk
