### ISSUE TITLE
Челны

### ISSUE THREAD

**Issue by Kavocha** [ornalogy/static-world-map.ornalogy.ru#4]
{
"title": "Челны"
"version": 1.0",
"center": [ 55.741272, 52.403662 ],
"markers": {
"IndustrialID1": [ 5, 55.770952, 52.435058 ],
"IndustrialID2": [ 5, 55.774703, 52.427620 ],
"IndustrialID3": [ 5, 55.767003, 52.424451 ],
"IndustrialID4": [ 5, 55.764605, 52.431805 ],
"IndustrialID5": [ 5, 55.766729, 52.424727 ],
}
}

**Comment by IgorNovozhilov** [comment]
https://static-world-map.ornalogy.ru/?naberezhnye-chelny
