### ISSUE TITLE
Тула тест

### ISSUE THREAD

**Issue by tangledjedi** [ornalogy/static-world-map.ornalogy.ru#6]
{
  "title": "Тула",
  "version": "1.0",
  "center": [ <latitude>, <longitude> ],
  "markers": {
    "arcanist_1": [ 7, 54.1921167, 37.5968805 ],
    "bazar_1": [ 10, 54.1427234, 37.5827891 ],
    "dungeon_1": [ 5, 54.174834, 37.587411],
    "dungeon_2": [5, 54.1885084, 37.5994678],
    "dungeon_3": [5, 54.1885084, 37.5994678].
    "dungeon_4": [5, 54.1908435, 37.6141822],
    "arena_1": [14, 54.1888802, 37.6210512],
  }
}

**Comment by 4monya** [comment]
Центр карты

"center": [ 54.193122, 37.617348, ],

**Comment by IgorNovozhilov** [comment]
https://static-world-map.ornalogy.ru/?tula
